dvmp:generate:
  needs: ["common:detector"]
  image: eicweb.phy.anl.gov:4567/monte_carlo/lager/lager:unstable
  extends: .phy_benchmark
  stage: generate
  timeout: 1 hours
  script:
    - run_many.py ./benchmarks/dvmp/gen.sh 
          -c jpsi_barrel 
          -e 10x100 
          --decay muon --decay electron
          --nproc 5

dvmp:process:
  stage: process
  extends: .phy_benchmark
  needs: ["common:detector", "dvmp:generate"]
  timeout: 2 hour
  script:
    - ls -lrth
    - compile_analyses.py dvmp
    - ls -lrth
    - run_many.py ./benchmarks/dvmp/dvmp.sh 
          -c jpsi_barrel 
          -e 10x100 
          --decay muon --decay electron
          --leading jpsi
          --nproc 5
  retry:
    max: 2
    when:
      - runner_system_failure

dvmp:results:
  stage: collect
  needs: ["dvmp:process"]
  script:
    - collect_tests.py dvmp
